### ISSUE TITLE
Changing HTTP port

### ISSUE THREAD

**Issue by screendriver** [ericbarch/dockuwiki#3]
Hi,

would it be possible to change the HTTP port? For example I would like to change the port to 8080 and set up my Router to forward the public available port 80 to the internal Raspberry Pi port 8080.

Why? Because I already running a service on my Raspberry Pi that uses port 80 and I can't change that. Furthermore this other service should not be available from the internet.

**Comment by ericbarch** [comment]
You should be able to change the port via the docker command you use to fire up the container.

From the example:

docker run -d --restart=always --name=wiki -e SSH_DOMAIN=bitbucket.org -e REMOTE_URL=git@bitbucket.org:YOUR_BITBUCKET_USERNAME/wiki.git -p 3000:3000 ericbarch/dockuwiki

Simply change the -p 3000:3000 to -p 8080:3000

**Comment by screendriver** [comment]
Great! Thank you for your help (I'm new to the "Docker land" 😉) Unfortunately I get another error: https://github.com/ericbarch/dockuwiki/issues/4
